import { nanoid } from "nanoid";
import { colors } from "./components/colors.js";

export const cardList = [
  {
    id: nanoid(),
    classTypeColor: colors.orange.background,
    classTypeCard: colors.orange.color,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23", 
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: colors.orange.background,
    classTypeCard: colors.orange.color,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: colors.purple.background,
    classTypeCard: colors.purple.color,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: colors.purple.background,
    classTypeCard: colors.purple.color,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: colors.orange.background,
    classTypeCard: colors.orange.color,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: nanoid(),
    classTypeColor: colors.green.background,
    classTypeCard: colors.green.color,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
];
