import { nanoid } from "nanoid";

export const cardList = [
  {
    id: nanoid(),
    classTypeColor: "card__theme _orange",
    classTypeCard: "_orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _orange",
    classTypeCard: "_orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _purple",
    classTypeCard: "_purple",
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _purple",
    classTypeCard: "_purple",
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _orange",
    classTypeCard: "_orange",
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: nanoid(),
    classTypeColor: "card__theme _green",
    classTypeCard: "_green",
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
];
